### ISSUE TITLE
[Dev] API 문서 - Swagger-UI 적용 

### ISSUE THREAD

**Issue by Bumnote** [feedback-forest/sijak-api#59]
### 📝 작업 내용 및 설명 
<hr>
프로젝트를 진행하면서 포스트맨을 사용하여 API 문서화를 진행했었습니다. 그러나, API를 수정하게 되었을 때 포스트맨에 다시 수정된 내용을 반영해야 하는 것에 작은 불편함을 느꼈습니다. 이러한 불편함을 해결하기 위해서 Swagger를 도입하기로 결심했고, 프론트엔드 개발자와 보다 더 원활한 소통을 할 수 있도록 작업 진행 중입니다.

### ✔️ TO-DO
<hr>

### kakao-user-controller

- [ ] POST /api/nickname 
- [ ] POST /api/nickname/validate 
- [ ] POST /api/logout 
- [ ] POST /api/agree 
- [ ] GET /api/mypage
- [ ] PATCH /api/mypage
- [ ] PATCH /api/mypage/address
- [ ] GET /login/callback 
- [ ] GET /api/user/{id} 
  
### token-controller

- [ ] POST /api/login 

### lecture-controller

- [ ] POST /api/location
- [ ] POST /api/lectures
- [ ] POST /api/lectures/{id}
- [ ] POST /api/home

### heart-controller

- [ ] GET /api/hearts
- [ ] POST /api/hearts
- [ ] DELETE /api/hearts
- [ ] DELETE /api/hearts/deactivates

### 기타
<hr>

[ Swagger-UI version ] 

- implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
