### ISSUE TITLE
[Dev] 실배포 이후 얻은 기술적 피드백 내용

### ISSUE THREAD

**Issue by Bumnote** [feedback-forest/sijak-api#64]
### 📝 작업 내용 및 설명 
<hr>

실배포 이후 팀원, 주변 지인, 개발자 분들에게 얻은 추가하면 좋을 피드백 내용입니다. 
하나씩 개선해나가려고 합니다. 

### ✔️ TO-DO
<hr>

- [ ]  쿠키 유효시간이 지났을 경우 -> 시간 연장 처리 
- [ ]  랜덤 닉네임에 랜덤 숫자 부여 ex) 멋쟁이사자#1234
- [ ]  랜덤 닉네임 형용사, 명사 추가 
- [ ]  회원가입 로직 Redis 도입 
- [ ]  검색 기능 추가 -> QueryDsl 사용 예정 
- [ ]  연령대를 기준으로 추천 시스템
- [ ]  프로필 사진 S3로 임의 사진 배정 (현재는 수작업으로 진행 중)
- [ ]  카테고리 자동화 기능  
- [ ]  모바일 통화 기능 
- [ ]  카카오 공유하기  

### 기타
<hr>

### Reference 
<hr>
